---
abstract: 'parse the data files of the Tomoe project'
author:
  - 'Ben Bullock <bkb@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.88, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Kanji-Tomoe
no_index:
  directory:
    - t
    - inc
requires:
  XML::Parser: 0
  perl: 5.008001
resources:
  bugtracker: https://github.com/benkasminbullock/Data-Kanji-Tomoe/issues
  repository: https://github.com/benkasminbullock/Data-Kanji-Tomoe
version: 0.04
